/**
 * Built-in trial playlists — pre-cached, preview-verified track data.
 *
 * Generated by scripts/fetch-builtin-playlists.mjs (every track verified to
 * have a working 30s preview via the same iTunes lookup /api/preview uses
 * at runtime). Re-run the script + redeploy to refresh.
 */

import type { Track } from "@/types";
import data from "./builtin-playlists-data.json";

export interface BuiltinPlaylist {
  id: string;
  name: string;
  description: string;
  coverEmoji: string;
  tracks: Track[];
}

interface BuiltinPlaylistsData {
  generatedAt: string;
  verified: boolean;
  playlists: BuiltinPlaylist[];
}

const typedData = data as BuiltinPlaylistsData;

export const BUILTIN_PLAYLISTS: BuiltinPlaylist[] = typedData.playlists;

export const BUILTIN_PLAYLISTS_GENERATED_AT = typedData.generatedAt;
export const BUILTIN_PLAYLISTS_VERIFIED = typedData.verified;
